version: '3.2'
services: 
  terraria-server-rocky:
    image: hexlo/terraria-server-docker:rocky-test
    container_name: terraria-server-rocky
    restart: unless-stopped
    networks:
      - traefik_net
    stdin_open: true
    tty: true     
    ports:
      - 7783:7777
    volumes:
      - type: bind
        source: ./worlds
        target: /root/.local/share/Terraria/Worlds/
    environment:
      - world=/root/.local/share/Terraria/Worlds/newworld.wld
      - password=dnf
      - motd="Welcome to North's server! :)"
    labels:
      com.centurylinklabs.watchtower.enable: true
      
networks:
  traefik_net:
    external: true
